// Svelte/src/LivroForm.svelte
<form on:submit|preventDefault={submit}>
	<h2>Novo Cadastro</h2>
	<Input label="Título" bind:value={book.statement} on:input={touched['statement']=true} on:blur={e=>
	checkField('statement')} placeholder="Digite o Título do livro" isRequired="true" error={errors['statement']} />
	<Input label="Autor" bind:value={book.autor} on:input={e=> touched['autor']=true} on:blur={e =>
	checkField('autor')} placeholder="Digite o nome do Autor" isRequired="true" error={errors['autor']} />
	<Input type="textarea" label="Descrição" bind:value={book.descricao} on:input={e=> touched['descricao']=true} on:blur={e =>
	checkField('descricao')} placeholder="Digite um breve resumo do livro" error={errors['descricao']} />
	<Input type="textarea" label="Link" bind:value={book.imagem} on:input={e=> touched['imagem']=true} on:blur={e =>
	checkField('imagem')} placeholder="Digite o link para download" isRequired="true" />
	<input type="submit" value="Cadastrar">
	<button type="button" on:click={e=> dispatch('cancel')}>Cancelar</button>
</form>

<script>
  import {requiredValidation} from './validations.js'
  import { createEventDispatcher } from 'svelte'
  import Input from './Input.svelte'

  export let livro
  const validate = {
    statement: requiredValidation,
    autor: requiredValidation,
    imagem: requiredValidation
  }
  let errors = {}
  let touched = {}
  const dispatch = createEventDispatcher()

  const { statement, autor, descricao, imagem } = livro || {}
  let book = { statement, autor, descricao, imagem}

  function checkField(name) {
    errors[name] = ''
    if (validate[name] && touched[name]) {
      const value = book[name]
      errors[name] = validate[name](value) || ''
    }
  }

  function submit() {
    Object.keys(book).forEach(field => {
      touched[field] = true
      checkField(field)
    })
    const errorsIsEmpty = !Object.values(errors).some(v => v)
    if (errorsIsEmpty) {
      dispatch('update', {
        statement: book.statement,
        autor: book.autor,
        descricao: book.descricao,
        imagem:book.imagem
      })
    }
  }
</script>

// React/src/LivroForm.js
import React from 'react'
import Input from './forms/Input'
import {requiredValidation} from './forms/validations'


const validate = {
    statement: requiredValidation,
    autor: requiredValidation,
    descricao: requiredValidation,
    imagem: requiredValidation
  }

export default class LivroForm extends React.Component{
    constructor(props) {
      super(props)
      this.state = {
        livro: {  
            statement: props.livro.statement || '', //titulo do livro
            autor:  props.livro.autor || '',
            descricao: props.livro.descricao || '',
            imagem: props.livro.imagem || ''
        },
        errors: {},
        touched: {}
      }
      this.onChange = this.onChange.bind(this)
      this.onBlur = this.onBlur.bind(this)
      this.onSubmit = this.onSubmit.bind(this)
      this.onCancel = this.onCancel.bind(this)
    }

    onChange(event) {
        const { name, value } = event.target
        this.setState((state) => ({
          ...state,
          livro: { ...state.livro, [name]: value },
          touched: { ...state.touched, [name]: true }
        }))
    }

    onBlur(event) {
        const { name, value } = event.target
        const { [name]: removedError, ...rest } = this.state.errors
        const error = validate[name] ? validate[name](value) : null
        const nameError = this.state.touched[name] ? error : null
    
        this.setState((state) => ({
          ...state,
          errors: {
            ...rest,
            [name]: nameError
          }
        }))
    }
    
    onSubmit(event) {
        event.preventDefault()
        const livro = this.state.livro

        const validation = Object.keys(livro).reduce((acc, key) => {
          const error = validate[key] && validate[key](livro[key])
          return {
            errors: {
              ...acc.errors,
              ...(error && { [key]: error })
            },
            touched: {
              ...acc.touched,
              ...{ [key]: true }
            }
          }
        }, {})
        this.setState((state) => ({
          ...state,
          errors: validation.errors,
          touched: validation.touched
        }))
    
        const errorValues = Object.values(validation.errors)
        const touchedValues = Object.values(validation.touched)
        const errorsIsEmpty = errorValues.length === 0
        const touchedAll = touchedValues.length === Object.values(livro).length
        const allTrue = touchedValues.every((t) => t === true)
        if (errorsIsEmpty && touchedAll && allTrue) {
          this.props.onUpdate({
            statement: livro.statement,
            autor:livro.autor,
            descricao:livro.descricao,
            imagem:livro.imagem
          })
        }
        console.log(this.state)
    }

    onCancel(event) {
      this.props.onCancel()
    }

    render() {
        const commonProps = {
          values: this.state.livro,
          errors: this.state.errors,
          touched: this.state.touched,
          onChange: this.onChange,
          onBlur: this.onBlur
        }
        return (
          <form onSubmit={this.onSubmit}>
            <h2>Adicionar</h2>
            <Input
              label="Título"
              name="statement"
              placeholder="Digite o título do livro"
              isRequired={true}
              {...commonProps}
            />
            <Input
              label="Autor(a)"
              name="autor"
              placeholder="Digite o nome do(a) autor(a) do livro"
              isRequired={true}
              {...commonProps}
            />
            <Input
              type="textarea"  
              label="Descrição"
              name="descricao"
              placeholder="Digite uma breve descrição da obra"
              isRequired={true}
              {...commonProps}
            />
            <Input
              type="textarea"  
              label="Link"
              name="imagem"
              placeholder="Insira o link da imagem do livro ou da página para download do e-book"
              isRequired={true}
              {...commonProps}
            />
            <input type="submit" value="Cadastrar" />
            <button onClick={this.onCancel}>Cancelar</button>
          </form>
        )
    }
}
