// React/biblioteca/src/Livro.js
import React from 'react'

export default class Livro extends React.Component {
  render() { 
    return (
      <div>
        <img src={this.props.imagem} alt="Falha ao carregar" width={60} height={40}/>
        <h1>{this.props.statement}</h1>
        <h3>{this.props.autor}</h3>
        <p>{this.props.descricao}</p>
      </div>
    )
  }
}

// Svelte/src/Livro.svelte
<img src={imagem} alt="Falha ao carregar" width={100} height={140}/>
<h1>{ statement }</h1>
<h2>{ autor }</h2>
<h4>{ header }</h4>
<p>{ descricao }</p>

<script>
  let header = "Descrição";
  export let statement;
  export let autor;
  export let descricao;
  export let imagem;
</script>
