// Svelte/src/App.svelte
<script>
    import Biblioteca from "./Biblioteca.svelte";
    import ListaLivro from "./ListaLivro.svelte";
    import LivroForm from "./LivroForm.svelte";
    
</script>

<style>
    body {
    font-family: sans-serif;
    background-image: url(https://i.pinimg.com/originals/c4/d1/e0/c4d1e083acbdb201927e50b2486283b1.png);
    opacity: 0.9;
    }
    .principal{
    font-size: 22px;
    background-color: #FFFFFF;
    margin: 450px 150px;
    }
    .container{
    display: flex;
    width: 100%;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: space-around;
    align-content: center;
    margin-bottom: 30px;
    }
    .category {
    width: 25%;
    margin: 30px 1.53333%;
    border: 5px solid #fff;
    background: #fff;
    line-height: 35px;
    box-shadow: 0 10px 20px #999;
    display: inline-block;
    }
    .imagem {
    width: 100%;
    height: 150px;
    background: black;
    }
    .panel {
    background-color: #C0C0C0;
    padding: 10px;
    border: 5px solid #fff;
    }
</style>

<main>
    <body>
        <div class="principal">
            <h1>Biblioteca Virtual</h1>
            <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Praesent sodales felis nec lacinia dapibus.
            Praesent tempus turpis ipsum, sit amet iaculis nisi tempor sed.
            Donec sit amet justo eu dolor varius consequat sit amet non felis.
            Cras luctus convallis blandit. Donec eget iaculis ipsum.
            Phasellus ligula neque, convallis in dictum ac, cursus non neque.
            Integer sit amet convallis turpis, in fringilla tortor.
            Curabitur interdum neque sed volutpat vestibulum.
            Aliquam erat volutpat. Nulla sit amet pulvinar orci, at pellentesque dolor.
            Proin fringilla id felis sed egestas.
            Aliquam molestie sit amet orci ac consequat.
            </p>
            <div class="container">
                <div class="category">
                    <img class="imagem" src="https://www.estudarfora.org.br/app/uploads/2013/10/20131029_livros_115791277-768x334.jpg" alt="Falha ao carregar" width={150} height={40}/>
                    <h3>Livros</h3>
                </div>
                <div class="category">
                    <img class="imagem" src="https://www.estudarfora.org.br/app/uploads/2013/10/20131029_livros_115791277-768x334.jpg" alt="Falha ao carregar" width={150} height={40}/>
                    <h3>E-books</h3>
                </div>
                <div class="category">
                    <img class="imagem" src="https://www.estudarfora.org.br/app/uploads/2013/10/20131029_livros_115791277-768x334.jpg" alt="Falha ao carregar" width={150} height={40}/>
                    <h3>Cadastro</h3>
                </div>
            </div>

            <div>
            <div class="panel">
                <Biblioteca/>
            </div>
            <div class="panel">
                <h1>Cadastro (Em manutenção)</h1>
                <LivroForm/>
            </div>
            <div class="panel">
                <h1>E-books</h1>
                <ListaLivro/>
            </div>
            </div>
        </div>
    </body>
  
</main>

// Vue/src/App.vue
<template>
  <div class="principal">
    <header>
      <h1>Biblioteca Virtual</h1>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Praesent sodales felis nec lacinia dapibus.
      Praesent tempus turpis ipsum, sit amet iaculis nisi tempor sed.
      Donec sit amet justo eu dolor varius consequat sit amet non felis.
      Cras luctus convallis blandit. Donec eget iaculis ipsum.
      Phasellus ligula neque, convallis in dictum ac, cursus non neque.
      Integer sit amet convallis turpis, in fringilla tortor.
      Curabitur interdum neque sed volutpat vestibulum.
      Aliquam erat volutpat. Nulla sit amet pulvinar orci, at pellentesque dolor.
      Proin fringilla id felis sed egestas.
      Aliquam molestie sit amet orci ac consequat.
      </p>
      <div class="container">
        <div class="category">
          <img class="imagem" src="https://www.estudarfora.org.br/app/uploads/2013/10/20131029_livros_115791277-768x334.jpg" alt="Falha ao carregar" width={150} height={40}/>
          <h3>Livros</h3>
        </div>
        <div class="category">
        <img class="imagem" src="https://www.estudarfora.org.br/app/uploads/2013/10/20131029_livros_115791277-768x334.jpg" alt="Falha ao carregar" width={150} height={40}/>
          <h3>E-books</h3>
        </div>
        <div class="category">
        <img class="imagem" src="https://www.estudarfora.org.br/app/uploads/2013/10/20131029_livros_115791277-768x334.jpg" alt="Falha ao carregar" width={150} height={40}/>
          <h3>Cadastro</h3>
        </div>
      </div>
    </header>
    <div>
      <div class="panel">
        <Biblioteca/>
      </div>
      <div class="panel">
        <h1>Cadastro (Em manutenção)</h1>
        <LivroForm/>
      </div>
      <div class="panel">
        <h1>E-books</h1>
        <ListaLivro/>
      </div>
    </div>
  </div>
</template>

<script>
import Biblioteca from './components/Biblioteca.vue'
import LivroForm from './components/LivroForm.vue'
import ListaLivro from './components/ListaLivro.vue'

export default {
  name: 'App',
  components: {
    Biblioteca,
    LivroForm,
    ListaLivro
  }
}
</script>

<style>
body {
  font-family: sans-serif;
  background-image: url(https://i.pinimg.com/originals/c4/d1/e0/c4d1e083acbdb201927e50b2486283b1.png);
  opacity: 0.9;
}
Input[type=text]{
  width: 300px;
}
.selected {
  font-weight: bold;
}
.principal{
  font-size: 22px;
  background-color: #FFFFFF;
  margin: 450px 150px;
}
.container{
  display: flex;
  width: 100%;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-around;
  align-content: center;
  margin-bottom: 30px;
}
.category {
  width: 25%;
  margin: 30px 1.53333%;
  border: 5px solid #fff;
  background: #fff;
  line-height: 35px;
  box-shadow: 0 10px 20px #999;
  display: inline-block;
}
.imagem {
  width: 100%;
  height: 150px;
  background: black;
}
.panel {
  background-color: #C0C0C0;
  padding: 10px;
  border: 5px solid #fff;
}
.m5 {
  margin: 50px;
}
</style>
