// React/src/Livro.js
import React from 'react'

export default class Livro extends React.Component {
  render() { 
    return (
      <div>
        <img src={this.props.imagem} alt="Falha ao carregar" width={150} height={240}/>
        <h1>Livro: {this.props.statement}</h1>
        <h2>Autor: {this.props.autor}</h2>
        <h4>Descrição:</h4>
        <p className="paragrafo">{this.props.descricao}</p>
      </div>
    )
  }
}

// Angular/src/app/livro.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "livro",
  template: `<div class="classeLivro">
    <img src={{imagem}} alt="Falha ao carregar" width={100} height={140}/>
    <h1>{{ statement }}</h1>
    <h2>{{ autor }}</h2>
    <h4>{{ header }}</h4>
    <p class="paragrafo">{{ descricao }}</p>    
  </div>`
})
export class LivroComponent {
  @Input() statement: string;
  @Input() autor: string;
  header = "Descrição";
  @Input() descricao: string;
  @Input() imagem: string;
}
